# use_frameworks!

platform :ios, '12.4'
source 'https://github.com/RichieZhl/Spec.git'
source 'https://github.com/CocoaPods/Specs.git'

require_relative '../react_native_pods'

target 'RNBaseController_Example' do
  pod 'RNBaseController', :path => '../'

  use_react_native!(
    :react_version => "0.71.2",
    :flipperkit_version => '0.125.0'
  )
  post_install do |installer|
    react_native_post_install(installer)
  end

#  post_install do |installer|
#    if defined? installer.pods_project
#      installer.pods_project.targets.each do |target|
#          if target.name == 'React'
#            target.build_configurations.each do |config|
#                config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
#            end
#          end
#
#          if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
#            target.build_configurations.each do |config|
#                config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
#            end
#          end
#      end
#    end
#  end

  target 'RNBaseController_Tests' do
    inherit! :search_paths

    
  end
end
