use_frameworks!

platform :ios, '9.0'
source 'https://github.com/RichieZhl/Spec.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'RNBaseController_Example' do
  pod 'RNBaseController', :path => '../'

  target 'RNBaseController_Tests' do
    inherit! :search_paths

    
  end
end
